 const MoreProductsData = [
  {
    id: 1,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 2,
    img: "https://cdn.shopify.com/s/files/1/0101/4832/products/Angela_Natural_Tee.png?v=1606780388",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 3,
    img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 4,
    img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },

  {
    id: 5,
    img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 6,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 7,
    img: "https://images.unsplash.com/photo-1552664199-fd31f7431a55?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 8,
    img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 9,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgipYslUbkjjd6nn-S8tVZ2eK6kPMQV9cvDQ&usqp=CAU",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 10,
    img: "https://i.ibb.co/DG69bQ4/2.png",
    ttitle: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 11,
    img: "https://i.ibb.co/cXFnLLV/3.png",
    title: "name",
    desc: "used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "name",
    desc: "  used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 13,
    img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "name",
    desc: "  used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 14,
    img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
  {
    id: 15,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtxQJE0njCUlufji0bqAj7fDdqdYZlkJyf-g&usqp=CAU",
    title: "name",
    desc: " used for this with 10% off and made up of recycled product",
    price: "₹120",
  },
];
export default MoreProductsData;
